fetch('search.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{
 const q=document.querySelector('#search'),year=document.querySelector('#year'),sup=document.querySelector('#supervisor'),cards=[...document.querySelectorAll('article[data-id]')];
 const option=(s,v,t)=>{const o=document.createElement('option');o.value=v;o.textContent=t;s.append(o)};
 [...new Set(data.map(p=>p.year))].sort().reverse().forEach(y=>option(year,y,y));
 const names=new Map();data.forEach(p=>p.supervisors.forEach(s=>names.set(s.search_key,s.name)));[...names].sort().forEach(([k,v])=>option(sup,k,v));
 function render(){const query=q.value.trim().toLowerCase();const filtered=data.filter(p=>(!year.value||p.year===year.value)&&(!sup.value||p.supervisors.some(s=>s.search_key===sup.value))&&(!query||[p.title,...p.terms,...p.supervisors.map(s=>s.name)].join(' ').toLowerCase().includes(query)));const ids=new Set(filtered.map(p=>p.id));cards.forEach(c=>c.hidden=!ids.has(c.dataset.id));document.querySelector('#count').textContent=`${filtered.length} of ${data.length} projects`;
 const counts=new Map(),ys=new Map();filtered.forEach(p=>{new Set(p.terms).forEach(t=>counts.set(t,(counts.get(t)||0)+1));ys.set(p.year,(ys.get(p.year)||0)+1)});const top=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,40);const cloud=document.querySelector('#cloud');cloud.replaceChildren();top.forEach(([t,n])=>{const b=document.createElement('button');b.textContent=t;b.title=`${n} projects`;b.setAttribute('aria-label',`${t}: ${n} projects. Search this term`);b.style.fontSize=`${14+22*Math.sqrt(n/(top[0]?.[1]||1))}px`;b.onclick=()=>{q.value=t;render()};cloud.append(b)});const bars=document.querySelector('#years');bars.replaceChildren();[...ys].sort().forEach(([y,n])=>{const s=document.createElement('span');s.textContent=`${y}: ${n}`;bars.append(s)})}
 q.addEventListener('input',render);year.onchange=render;sup.onchange=render;document.querySelector('#reset').onclick=()=>{q.value=year.value=sup.value='';render()};render();
}).catch(()=>{document.querySelector('#count').textContent='Interactive filters are unavailable. You can still browse all projects below.'});
